//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumericMethods.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumericMethods.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        internal static string Common_Calculate {
            get {
                return ResourceManager.GetString("Common_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykres.
        /// </summary>
        internal static string Common_Chart {
            get {
                return ResourceManager.GetString("Common_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomoc.
        /// </summary>
        internal static string Common_Help {
            get {
                return ResourceManager.GetString("Common_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź dane.
        /// </summary>
        internal static string Common_InputData {
            get {
                return ResourceManager.GetString("Common_InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędna funkcja.
        /// </summary>
        internal static string Common_InvalidFunction {
            get {
                return ResourceManager.GetString("Common_InvalidFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja nie może przyjmować kilku wartości dla jednego argumentu..
        /// </summary>
        internal static string Common_InvalidFunction_Message {
            get {
                return ResourceManager.GetString("Common_InvalidFunction_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        internal static string Common_Result {
            get {
                return ResourceManager.GetString("Common_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak.
        /// </summary>
        internal static string Common_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Common_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups!.
        /// </summary>
        internal static string Common_Ups {
            get {
                return ResourceManager.GetString("Common_Ups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja funkcja zawiera błędy. Spróbuj jeszcze raz!.
        /// </summary>
        internal static string Common_WrongFunction {
            get {
                return ResourceManager.GetString("Common_WrongFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzielenie przez zero jest niedozwolone..
        /// </summary>
        internal static string FunctionResponse_DivideByZero_Message {
            get {
                return ResourceManager.GetString("FunctionResponse_DivideByZero_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja funkcja zawiera niezamknięte nawiasy. Spróbuj jeszcze raz..
        /// </summary>
        internal static string FunctionResponse_UnclosedParentheses_Message {
            get {
                return ResourceManager.GetString("FunctionResponse_UnclosedParentheses_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja funkcja zawiera błędy, które należy poprawić..
        /// </summary>
        internal static string FunctionResponse_WrongFunction_Message {
            get {
                return ResourceManager.GetString("FunctionResponse_WrongFunction_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Aby użyć potęgi we wzorze, konieczne jest użycie znaku ^. Przykładowy wzór funkcji: x^4+7x^2-4.
        /// </summary>
        internal static string HelpPage_Power {
            get {
                return ResourceManager.GetString("HelpPage_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Podaj własną dokładność całkowania.
        /// </summary>
        internal static string IntegralPage_CustomPrecision {
            get {
                return ResourceManager.GetString("IntegralPage_CustomPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Podaj wzór funkcji.
        /// </summary>
        internal static string IntegralPage_Formula {
            get {
                return ResourceManager.GetString("IntegralPage_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Podaj dolną granicę całkowania.
        /// </summary>
        internal static string IntegralPage_LowerLimit {
            get {
                return ResourceManager.GetString("IntegralPage_LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Wybierz dokładność całkowania.
        /// </summary>
        internal static string IntegralPage_Precision {
            get {
                return ResourceManager.GetString("IntegralPage_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz poziom dokładności.
        /// </summary>
        internal static string IntegralPage_Precision_PickerTitle {
            get {
                return ResourceManager.GetString("IntegralPage_Precision_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Podaj górną granicę całkowania.
        /// </summary>
        internal static string IntegralPage_UpperLimit {
            get {
                return ResourceManager.GetString("IntegralPage_UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string LinearChart_AxisXDescription {
            get {
                return ResourceManager.GetString("LinearChart_AxisXDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string LinearChart_AxisYDescription {
            get {
                return ResourceManager.GetString("LinearChart_AxisYDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y₁ = {0}.
        /// </summary>
        internal static string LinearChart_FirstFunction {
            get {
                return ResourceManager.GetString("LinearChart_FirstFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje.
        /// </summary>
        internal static string LinearChart_LegendTitle {
            get {
                return ResourceManager.GetString("LinearChart_LegendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y₂ = {0}.
        /// </summary>
        internal static string LinearChart_SecondFunction {
            get {
                return ResourceManager.GetString("LinearChart_SecondFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikacji.
        /// </summary>
        internal static string Menu_AboutApp {
            get {
                return ResourceManager.GetString("Menu_AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równania różniczkowe.
        /// </summary>
        internal static string Menu_DifferentialEquation {
            get {
                return ResourceManager.GetString("Menu_DifferentialEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całkowanie numeryczne.
        /// </summary>
        internal static string Menu_Integral {
            get {
                return ResourceManager.GetString("Menu_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolacja.
        /// </summary>
        internal static string Menu_Interpolation {
            get {
                return ResourceManager.GetString("Menu_Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Równania liniowe.
        /// </summary>
        internal static string Menu_LinearEquation {
            get {
                return ResourceManager.GetString("Menu_LinearEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcje nieliniowe.
        /// </summary>
        internal static string Menu_NonLinearEquation {
            get {
                return ResourceManager.GetString("Menu_NonLinearEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y₀ = {0}.
        /// </summary>
        internal static string NonLinearChart_Function {
            get {
                return ResourceManager.GetString("NonLinearChart_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja.
        /// </summary>
        internal static string NonLinearChart_LegendTitle {
            get {
                return ResourceManager.GetString("NonLinearChart_LegendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz dokładność metody obliczającej.
        /// </summary>
        internal static string NonLinearEquation_Precision {
            get {
                return ResourceManager.GetString("NonLinearEquation_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość dokładności całkowania nie może być pusta.
        /// </summary>
        internal static string Validation_CustomPrecisionIsEmpty {
            get {
                return ResourceManager.GetString("Validation_CustomPrecisionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole nie może być puste.
        /// </summary>
        internal static string Validation_FieldEmpty {
            get {
                return ResourceManager.GetString("Validation_FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wzór funkcji zawiera błędy.
        /// </summary>
        internal static string Validation_FormulaIsNotValid {
            get {
                return ResourceManager.GetString("Validation_FormulaIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Górna granica całkowania musi być większa niż dolna granica.
        /// </summary>
        internal static string Validation_InvalidBorder {
            get {
                return ResourceManager.GetString("Validation_InvalidBorder", resourceCulture);
            }
        }
    }
}
